/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Font;
import javax.swing.*;
import java.io.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author Ivanes047
 */
public class NewJFrame extends javax.swing.JFrame {                       
    /**
     * Creates new form NewJFrame
     */
    
    
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextArea1.setFont(new Font("Arial", Font.PLAIN, 14));
        jTextArea1.setLineWrap(true);
        File file = new File("Дневник");
        if(!file.exists()){
            file.mkdir();
        }
    }
    
    File file;
    javax.swing.filechooser.FileFilter fileFilterTxt = new SimpleFileFilter(".txt", "Text files");
    javax.swing.filechooser.FileFilter fileFilterDat = new SimpleFileFilter(".dat", "Data files");
    JFileChooser fileChooser = new javax.swing.JFileChooser();
    
    {
        fileChooser.addChoosableFileFilter(fileFilterDat);
        fileChooser.addChoosableFileFilter(fileFilterTxt);
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        openMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveASMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem1 = new javax.swing.JMenuItem();
        formatMenu1 = new javax.swing.JMenu();
        nachertMenu = new javax.swing.JMenu();
        PlainfontMenuItem = new javax.swing.JMenuItem();
        ItalicfontMenuItem = new javax.swing.JMenuItem();
        BoldfontMenuItem = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Дневник");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        fileMenu1.setText("Файл");

        openMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openMenuItem1.setText("Открыть...");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(openMenuItem1);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveMenuItem.setText("Сохранить как сегодняшний день...");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu1.add(saveMenuItem);

        saveASMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveASMenuItem1.setText("Сохранить как...");
        saveASMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveASMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(saveASMenuItem1);

        exitMenuItem1.setText("Выход");
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(exitMenuItem1);

        jMenuBar1.add(fileMenu1);

        formatMenu1.setText("Шрифт");

        nachertMenu.setText("Начертание");

        PlainfontMenuItem.setText("Обычный");
        PlainfontMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlainfontMenuItemActionPerformed(evt);
            }
        });
        nachertMenu.add(PlainfontMenuItem);

        ItalicfontMenuItem.setText("Курсив");
        ItalicfontMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalicfontMenuItemActionPerformed(evt);
            }
        });
        nachertMenu.add(ItalicfontMenuItem);

        BoldfontMenuItem.setText("Жирный");
        BoldfontMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoldfontMenuItemActionPerformed(evt);
            }
        });
        nachertMenu.add(BoldfontMenuItem);

        formatMenu1.add(nachertMenu);

        jMenuBar1.add(formatMenu1);

        helpMenu1.setText("Справка");
        helpMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(helpMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    int i = 1;
    int j = 1;
    
    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem1ActionPerformed
        fileChooser.setCurrentDirectory(new File("."));
        fileChooser.addChoosableFileFilter(fileFilterTxt);
        if (fileChooser.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;//Нажали Cancel
        }
        file = fileChooser.getSelectedFile();
        try {
            FileReader filReadStream = new FileReader(file);
            BufferedReader bufferedIn = new BufferedReader(filReadStream);
            String s="",tmpS="";
            while((tmpS = bufferedIn.readLine())!=null)
            s+=tmpS+"\n";
            jTextArea1.setText(s);
            bufferedIn.close();
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Ошибка чтения из файла \n" + file.getAbsolutePath());
        }
        
    }//GEN-LAST:event_openMenuItem1ActionPerformed

    private void exitMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItem1ActionPerformed

    
    private void saveASMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveASMenuItem1ActionPerformed
        //fileChooser.setFileFilter(fileFilter);
        if (fileChooser.showSaveDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;//Нажали Cancel
        }
        file = fileChooser.getSelectedFile();
        try {
            Writer filWriteStream = new FileWriter(file);
            filWriteStream.write(jTextArea1.getText());
            filWriteStream.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ошибка записи в файл \n" + file.getAbsolutePath());
        }   
    }//GEN-LAST:event_saveASMenuItem1ActionPerformed

    private void PlainfontMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlainfontMenuItemActionPerformed
        jTextArea1.setFont(new Font("Arial", Font.PLAIN, 14));
    }//GEN-LAST:event_PlainfontMenuItemActionPerformed

    private void ItalicfontMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalicfontMenuItemActionPerformed
        jTextArea1.setFont(new Font("Arial", Font.ITALIC, 14));
    }//GEN-LAST:event_ItalicfontMenuItemActionPerformed

    private void BoldfontMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoldfontMenuItemActionPerformed
        jTextArea1.setFont(new Font("Arial", Font.BOLD, 14));
    }//GEN-LAST:event_BoldfontMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        try {
            LocalDate localDate = LocalDate.now();
            File file = new File("./Дневник/"+ DateTimeFormatter.ofPattern("dd_MM_yyyy").format(localDate)+".txt");
            if(file.exists()){
                file.delete();
            }
            Writer filWriteStream = new FileWriter(new File(".").getAbsolutePath()+"//Дневник//" + DateTimeFormatter.ofPattern("dd_MM_yyyy").format(localDate) + ".txt",true);
            filWriteStream.write(jTextArea1.getText());
            filWriteStream.close();
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ошибка записи в файл \n" + file.getAbsolutePath());
        }    
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void helpMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenu1MouseClicked
        createFrame();
    }//GEN-LAST:event_helpMenu1MouseClicked
    
    protected void createFrame() {
        helpJFrame frame = new helpJFrame();
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BoldfontMenuItem;
    private javax.swing.JMenuItem ItalicfontMenuItem;
    private javax.swing.JMenuItem PlainfontMenuItem;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenu formatMenu1;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu nachertMenu;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem saveASMenuItem1;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    
}



